[package]
name = "nvim-bindgen"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
bindgen.workspace = true
libc.workspace = true
serde_json.workspace = true
winnow.workspace = true
